source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
#忽略引入库的警告
inhibit_all_warnings!

target 'OpenApplusSample' do
    pod 'OpenApplus', :podspec => './podspec/OpenApplus.podspec'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ARCHS'] = 'armv7 armv7s arm64'
            config.build_settings['VALID_ARCHS'] = 'armv7 armv7s arm64'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
